### ISSUE TITLE
Same Project with Obj- C

### ISSUE THREAD

**Issue by ranjitk-plackal** [Mozharovsky/iOS-Demos#1]
Hello,

Firstly thanks, for this tutorial, As I have still not started using swift, can you please create a Obj-C version of the project. It would help many people like me, who are maintaining Obj- C projects.

Thanks
Ranjit

**Comment by mozharovsky** [comment]
Hello @ranjitk-plackal , 

The objective-c version is added in 90d0c5835f1dcac3154b94fe96a3897dfca56592 revision. Now you can feel free to get familiar with Search Mechanism, enjoy. 

Regards, 
Eugene

**Comment by ranjitk-plackal** [comment]
Thanks
